### ISSUE TITLE
how to configure grizzled to log different log levels to different log files?

### ISSUE THREAD

**Issue by GioAgu17** [bmc/grizzled-slf4j#32]
I want to use two different log levels, trace and info, and log them to different log files. I saw that this is possible in Java, following this StackOverflow [question](https://stackoverflow.com/questions/1839647/how-to-configure-log4j-to-log-different-log-levels-to-different-files-for-the-sa).
Is there a way to do so in Grizzled with an SBT project? At the moment I can only output one log level to one file by creating a file "simplelogger.properties" following [this article](https://alvinalexander.com/scala/how-to-log-output-file-grizzled-slf4j-scala-simplelogger.properties).
Any help would be appreciated.
Thank you

**Comment by bmc** [comment]
`grizzled-slf4j` is _nothing more_ than a Scala language-friendly wrapper around the SLF4J API. Whatever works with your underlying SLF4J-compliant logger will work with this API. For instance, if you're using Logback, then you'd configure all this stuff in the `logback.xml` file. `grizzled-slf4j` knows nothing about the underlying logging framework (`logback`, `avsl`, whatever). It's just a very thin layer on top of SLF4J.
